In [7]:
import numpy as np

a= np.array([[1,2,3],[4,5,6]])

print('The original matrix is ', a)

# appending element 

print(f"After appending one element  at {a} it becomes ")
a=np.append(a,[7])

print(a)

# appending one array into other 

b=np.array([[12,23,34],[45,56,67]])

print("The second array is ", b)

print(f"After appending {b} to {a} it becomes")
a= np.append(a,b)
print(a)

# concatenation of two array 

ar1=np.array([1,2],[3,4])
ar2=np.array([[2,3]])

combined = np.concatenate((ar1,ar2),axis=0)

print(f"After combination of {ar1} and {ar2} ", combined)

The original matrix is  [[1 2 3]
 [4 5 6]]
After appending one element  at [[1 2 3]
 [4 5 6]] it becomes 
[1 2 3 4 5 6 7]
The second array is  [[12 23 34]
 [45 56 67]]
After appending [[12 23 34]
 [45 56 67]] to [1 2 3 4 5 6 7] it becomes
[ 1  2  3  4  5  6  7 12 23 34 45 56 67]


TypeError: Field elements must be 2- or 3-tuples, got '3'