In [10]:
# appending matrix using list comprehension 

import numpy as np

arr= np.array([1,2,3,4,5])

append =[ np.array([6,7]) , np.array([8,9])]

combined = np.concatenate([arr] + append)
print(combined)

a=np.arange(1,13).reshape(2,6)
print("original array is ", a)

# column wise reshaping 

cols = np.arange(5,11).reshape(1,6)

print("Array to be appended column wise ", cols)

arr_col = np.append(a,cols,axis=0)

print("After appending ", arr_col)

# swapping columns 

myarray = np.arange(12).reshape(4,3)

print("Newly created array  is ", myarray)

myarray[:,[2,0]] = myarray[:,[0,2]]

print("After swapping it becomes ", myarray)

[1 2 3 4 5 6 7 8 9]
original array is  [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Array to be appended column wise  [[ 5  6  7  8  9 10]]
After appending  [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 5  6  7  8  9 10]]
Newly created array  is  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After swapping it becomes  [[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]
