In [5]:
# swapping numbers with user choice 

import numpy as np

myarr = np.arange(12).reshape(4,3)
print("origial array")
print(myarr)

def swap(arr,start,last):

    arr[:,[start,last]] =  arr[:,[last,start]]

swap(myarr,0,1)
print("After swapping ")

print(myarr)

# array element wise manipulation 

a=np.array([1,2,3,4])
b=np.array([5,4,3,2])

c=a*b

print(f"the multiplication of {a} and {b} is ")
print(c)

# array broadcasting in a single dimesioal arrray 

a1=np.array([1,2,3,4])

b=3

print("Original array")
print(a1)

c=a1+b

print(f"After adding {b} to {a1} it becomes ")
print(c)


origial array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After swapping 
[[ 1  0  2]
 [ 4  3  5]
 [ 7  6  8]
 [10  9 11]]
the multiplication of [1 2 3 4] and [5 4 3 2] is 
[5 8 9 8]
Original array
[1 2 3 4]
After adding 3 to [1 2 3 4] it becomes 
[4 5 6 7]
