In [5]:
import numpy as np

v= np.array([1,2,3])
w=np.array([4,5])

# reshaping the array 

print(np.reshape(v,(3,1))*w)

x= np.array([[1,2,3],[4,5,6]])

# adding two matrix

print(x+v)

print("The transport version of the two mnatrix are ")

print((x.T + w).T)

print(x*2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
The transport version of the two mnatrix are 
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
