In [8]:
# soting and searching in numpy array 
import numpy as np

arr= np.array([1,10,3,4,5,6])

print("arr={}".format(arr))

# looking for  the given value 

i = np.where(arr == 3)

print("i={}".format(i))

# sorting in numpy 

arr.sort()

print("The sorted array is  ")

print(arr)

# sorting array in axis 0

a= np.array([[12,15],[8,99]])

arr1= np.sort(a,axis=0)

print(f"After sorting {a} it becomes  ")

print(arr1)

a = np.array([[10, 15], [12, 1]]) 

# sort along with last axis 
arr2 = np.sort(a,axis=-1)

print(arr2)

arr=[ 1 10  3  4  5  6]
i=(array([2], dtype=int64),)
The sorted array is  
[ 1  3  4  5  6 10]
After sorting [[12 15]
 [ 8 99]] it becomes  
[[ 8 15]
 [12 99]]
[[10 15]
 [ 1 12]]
