In [8]:
import numpy as np

a=np.arange(12)

a=a.reshape(3,4)

print("New matrix is", a)

# iterating through the array 

for x in np.nditer(a):
    
    print(x)

# transposing and ioterating through them 
a1 = np.array([[3,4],[4,5],[7,8]])

print(f"The transpose of the matrix {a1} is")
print(a1.T)

for y in np.nditer(a1):

    print(y)


New matrix is [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11
The transpose of the matrix [[3 4]
 [4 5]
 [7 8]] is
[[3 4 7]
 [4 5 8]]
3
4
4
5
7
8
