In [6]:
import numpy as np

a= np.arange(12)

a=a.reshape(3,4)
print("The original array is ", a)

# modifying the matrix

for x in np.nditer(a , op_flags=['readwrite']):
    x[...] =5*x

    print(x)

for y in np.nditer(a, flags=['external_loop'], order="C"):

    print(y)

The original array is  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
5
10
15
20
25
30
35
40
45
50
55
[ 0  5 10 15 20 25 30 35 40 45 50 55]
