In [9]:
 import numpy as np

A=np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

print("The new array is ")
print(A)

# rank of matrix 

print("The rank of the matrix ", np.linalg.matrix_rank(A))

# trace of the matrix 

print("The trace of the matrix is ", np.trace(A))
# determinant 

print(f"The determinant of the matrix {A} is  ", np.linalg.det(A))

print(f"Inverse of the matrix {A} is ", np.linalg.inv(A))

print(f"Matrix power of {A} ", np.linalg.matrix_power(A,3))

# eigen values 

a = np.array([[1, -2j], [2j, 5]])

print("Array is ")
print(a)

c,d  = np.linalg.eigh(a)
print("eigen values is ", c)
print("eigen values is ", d)


The new array is 
[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
The rank of the matrix  3
The trace of the matrix is  11
The determinant of the matrix [[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]] is   -306.0
Inverse of the matrix [[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]] is  [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
Matrix power of [[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]  [[336 162 228]
 [406 162 469]
 [698 702 905]]
Array is 
[[ 1.+0.j -0.-2.j]
 [ 0.+2.j  5.+0.j]]
eigen values is  [0.17157288 5.82842712]
eigen values is  [[-0.92387953+0.j         -0.38268343+0.j        ]
 [ 0.        +0.38268343j  0.        -0.92387953j]]
