In [6]:
# dot product 

import numpy as np

product = np.dot(5,4)
print("The dot product is ", product)

vector_a=2+3j
vector_b=3+2j

product = np.dot(vector_a,vector_b)

print(product)

product1 = np.vdot(vector_a,vector_b)
print(product1)

# generaitng rando float value 

out_arr = np.random.ranf(size=(2,1))

print(out_arr)

out_arr1 = np.random.ranf((3,3,2))
print(out_arr1)

# using random sample 

def sample():

    return  np.random.random_sample()

print(sample())

The dot product is  20
13j
(12-5j)
[[0.54059835]
 [0.51877527]]
[[[0.40207785 0.30568843]
  [0.97127526 0.56747867]
  [0.89325252 0.96513657]]

 [[0.86633252 0.63395338]
  [0.33748207 0.71003297]
  [0.2146625  0.66192101]]

 [[0.12674761 0.06141769]
  [0.1749297  0.98765468]
  [0.04760835 0.88808716]]]
0.10154834245156263
