In [9]:
import numpy as np

def generate():
     
     return  np.random.random_sample(size=(1,3))

print("Random values are ")
print(generate())

def swap():
     
     return np.random.random_sample((3,2,1))

print(swap())

# random integer 

our_array = np.random.random_integers(low=0,high=5,size=4)

print("Random integers ",our_array)

def ofgenerate():
     
     return np.random.random_integers(low=3,size=(3,3))

print("Integers are ",ofgenerate())

Random values are 
[[0.69952269 0.27796708 0.00159075]]
[[[0.26477763]
  [0.04403203]]

 [[0.8802894 ]
  [0.46678563]]

 [[0.88959032]
  [0.02030306]]]
Random integers  [5 5 4 4]
Integers are  [[3 2 3]
 [2 2 1]
 [2 3 2]]


C:\Users\subha\AppData\Local\Temp\ipykernel_10564\4158192344.py:18: DeprecationWarning: This function is deprecated. Please call randint(0, 5 + 1) instead
  our_array = np.random.random_integers(low=0,high=5,size=4)
C:\Users\subha\AppData\Local\Temp\ipykernel_10564\4158192344.py:24: DeprecationWarning: This function is deprecated. Please call randint(1, 3 + 1) instead
  return np.random.random_integers(low=3,size=(3,3))
