In [6]:
import numpy as np

def swap():

    return np.random.random_integers(1,6,(2,2,3))

print(swap())

# using randint 

def rand():

    return np.random.randint(low=0,high=3,size=5)

print(rand())

arr = np.random.randint(low=4,size=(2,3))

print(arr)

def generate():

    return np.random.randint(1,2,(4,3,10))

print(generate())

[[[2 3 6]
  [1 4 1]]

 [[3 6 6]
  [2 2 1]]]
[0 2 1 1 1]
[[1 0 2]
 [2 3 0]]
[[[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]]


C:\Users\subha\AppData\Local\Temp\ipykernel_9572\4197004291.py:5: DeprecationWarning: This function is deprecated. Please call randint(1, 6 + 1) instead
  return np.random.random_integers(1,6,(2,2,3))
