In [5]:
import random

sampleList  = [100,200,300,400,500]

weighted_list =random.choices(sampleList,weights=(10,20,30,40,50),k=5)

print(weighted_list)

[300, 300, 400, 500, 300]


In [6]:
import random

smaplelist  = [100,200,300,400,500]

list = random.choices(  smaplelist,cum_weights=(10,20,30,40,50), k=5)

print(list)

[400, 200, 400, 300, 400]


In [9]:
import numpy as np 

gfg = np.arange(10)

print("Before shuffle ", gfg)

print("After shuffle ")

np.random.shuffle(gfg)

print(gfg)



Before shuffle  [0 1 2 3 4 5 6 7 8 9]
After shuffle 
[2 8 5 7 1 6 4 9 3 0]


In [11]:
import numpy as np

gfg = np.arange(12).reshape(3,4)

print(gfg)

print("After reshaping")
np.random.shuffle(gfg)

print(gfg)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After reshaping
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
